version: '3'

services:
    
    mysql-server:
        image:                   mysql:5.7
        hostname:                ${DB_DATABASE}
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD} 
            MYSQL_ROOT_HOST:     ${MYSQL_ROOT_HOST}
        volumes:
            -                    ./db/dumps:/docker-entrypoint-initdb.d
            -                    ./db/data:/var/lib/mysql
        networks:
            -                    app-fullstack-net

    mysql-admin:
        image:                   phpmyadmin/phpmyadmin
        environment: 
            PMA_HOST:            ${PMA_HOST}
            PMA_PORT:            ${PMA_PORT}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        networks:
            -                    app-fullstack-net
        depends_on:
            -                    mysql-server
        ports:
            -                    "8001:80"

    node-backend:
        image:                   abassi/nodejs-server:10.0-dev
        volumes:
            -                    ./src:/home/node/app/src
        networks:
            -                    app-fullstack-net
        depends_on:
            -                    mysql-server
        ports: 
            -                    "8000:3000"
        command:                 nodemon /home/node/app/src/index.js

networks:
    app-fullstack-net:
        driver:                  bridge
